# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='delta_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
